### ISSUE TITLE
Panic in get_search_list when the SearchList registry key is missing

### ISSUE THREAD

**Issue by tynril** [liranringel/ipconfig#15]
On two different computers running Windows 10 version 1803 (OS build 17134.191), I encountered the following panic while running `cargo test`:

```
thread 'no_error' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Io(Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }), State { next_error: None, backtrace: Some(stack backtrace:
   0:     0x7ff743abc920 - backtrace::backtrace::trace<closure>
                        at C:\Users\tyn\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.9\src\backtrace\mod.rs:42
   1:     0x7ff743ab3f94 - backtrace::capture::Backtrace::new_unresolved
                        at C:\Users\tyn\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.9\src\capture.rs:88
   2:     0x7ff743ab3efd - backtrace::capture::Backtrace::new
                        at C:\Users\tyn\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.9\src\capture.rs:64
   3:     0x7ff743ab1ccc - error_chain::make_backtrace
                        at C:\Users\tyn\.cargo\registry\src\github.com-1ecc6299db9ec823\error-chain-0.8.1\src\lib.rs:413
   4:     0x7ff743ab1d8a - error_chain::{{impl}}::default
                        at C:\Users\tyn\.cargo\registry\src\github.com-1ecc6299db9ec823\error-chain-0.8.1\src\lib.rs:494
   5:     0x7ff743a8fdb8 - ipconfig::error::Error::from_kind
                        at E:\dev\ipconfig\<error_chain_processed macros>:49
   6:     0x7ff743a8fee3 - ipconfig::error::{{impl}}::from
                        at E:\dev\ipconfig\<error_chain_processed macros>:77
   7:     0x7ff743a9580a - ipconfig::computer::get_search_list
                        at E:\dev\ipconfig\src\computer.rs:52
   8:     0x7ff743a42fe3 - test::no_error
                        at E:\dev\ipconfig\tests\test.rs:7
   9:     0x7ff743a4244e - test::__test::TESTS::{{closure}}
                        at E:\dev\ipconfig\tests\test.rs:5
  10:     0x7ff743a419fb - core::ops::function::FnOnce::call_once<closure,()>
                        at C:\projects\rust\src\libcore\ops\function.rs:223
  11:     0x7ff743a4569e - alloc::boxed::{{impl}}::call_box<(),closure>
                        at C:\projects\rust\src\liballoc\boxed.rs:643
  12:     0x7ff743ae7fe2 - panic_unwind::__rust_maybe_catch_panic
                        at C:\projects\rust\src\libpanic_unwind\lib.rs:105
  13:     0x7ff743a5097b - std::sys_common::backtrace::__rust_begin_short_backtrace<closure,()>
                        at C:\projects\rust\src\libstd\sys_common\backtrace.rs:136
  14:     0x7ff743a5186e - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()>
                        at C:\projects\rust\src\libstd\panicking.rs:312
  15:     0x7ff743ae7fe2 - panic_unwind::__rust_maybe_catch_panic
                        at C:\projects\rust\src\libpanic_unwind\lib.rs:105
  16:     0x7ff743a58a15 - alloc::boxed::{{impl}}::call_box<(),closure>
                        at C:\projects\rust\src\liballoc\boxed.rs:642
  17:     0x7ff743ad04a2 - std::sys_common::thread::start_thread
                        at C:\projects\rust\src\libstd\sys_common\thread.rs:25
  18:     0x7ff743ad29e9 - std::sys::windows::thread::{{impl}}::new::thread_start
                        at C:\projects\rust\src\libstd\sys\windows\thread.rs:58
  19:     0x7ff8975e3034 - BaseThreadInitThunk) })', libcore\result.rs:983:5
```

On both computers, I do not have a `SearchList` subkey in `SYSTEM\CurrentControlSet\Services\Tcpip\Parameters`. I assume that it can be a valid state, since I didn't remove it manually.

I can work around this issue by creating an empty `SearchList` subkey at that location, but it's obviously not great.

**Comment by liranringel** [comment]
Closed by #16
